export const headingTexts: string[] = [
  "AI AUTOMATION",
  "AUTONOMOUS AGENTS",
  "CUSTOM SOFTWARE",
  "CLOUD INFRASTRUCTURE",
  "MOBILE PLATFORMS",
  "DEVOPS & ARCHITECTURE",
  "IT CONSULTING",
  "HIGH-PERFORMANCE WEB",
  "ENTERPRISE APIs",
  "INTELLIGENT SYSTEMS",
];
